/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.BukuDAO;
import model.Buku;

/**
 *
 * @author pedilz
 */
public class FormBuku extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBuku.class.getName());

    /**
     * Creates new form FormBuku
     */
    public FormBuku() {
        initComponents();
        txtId.setEditable(false); // ID tersembunyi
        loadTable();              // 🔥 INI WAJIB
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        lblPenulis = new javax.swing.JLabel();
        txtPenulis = new javax.swing.JTextField();
        lblPenerbit = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        lblTahunPenerbit = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        lblStok = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btn_Ubah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        ScrollBuku = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manajemen Buku");

        lblJudul.setText("Judul");

        txtJudul.addActionListener(this::txtJudulActionPerformed);

        lblPenulis.setText("Penulis");

        txtPenulis.addActionListener(this::txtPenulisActionPerformed);

        lblPenerbit.setText("Penerbit");

        txtPenerbit.addActionListener(this::txtPenerbitActionPerformed);

        lblTahunPenerbit.setText("Tahun Penerbit");

        lblStok.setText("Stok");

        txtStok.addActionListener(this::txtStokActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btn_Ubah.setText("Ubah");
        btn_Ubah.addActionListener(this::btn_UbahActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        txtId.setEditable(false);
        txtId.addActionListener(this::txtIdActionPerformed);

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        ScrollBuku.setViewportView(tblBuku);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(90, 90, 90)
                        .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addGap(80, 80, 80)
                        .addComponent(lblPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Ubah)
                            .addComponent(btnReset))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPenerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPenerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(txtPenulis, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJudul, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(lblTahunPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTahunPenerbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblPenulis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblPenerbit)
                .addGap(18, 18, 18)
                .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblStok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "ID", "Judul", "Penulis", "Penerbit", "Tahun", "Stok"
        });

        BukuDAO dao = new BukuDAO();
        for (Buku b : dao.getAll()) {
            model.addRow(new Object[]{
                b.getIdBuku(),
                b.getJudul(),
                b.getPenulis(),
                b.getPenerbit(),
                b.getTahunTerbit(),
                b.getStok()
            });
        }

        tblBuku.setModel(model);
    }
    


    
    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void txtPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenulisActionPerformed

    private void txtPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerbitActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        System.out.println("Tombol Simpan diklik");
        int tahunInt = 0;
        int stokInt = 0;
            // ambil input
        String judul = txtJudul.getText().trim();
        String penulis = txtPenulis.getText().trim();
        String penerbit = txtPenerbit.getText().trim();
        String tahun = txtTahun.getText().trim();
        String stok = txtStok.getText().trim();

        // 1. validasi kosong
        if (judul.isEmpty() || penulis.isEmpty() || penerbit.isEmpty() || tahun.isEmpty() || stok.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Semua field wajib diisi!",
                "Validasi",
                JOptionPane.WARNING_MESSAGE);
        return;
        }

        // 2. validasi angka
        try {
            tahunInt = Integer.parseInt(tahun);
            stokInt = Integer.parseInt(stok);

            // 3. validasi nilai logis
            if (tahunInt < 1900 || tahunInt > 2026) {
                JOptionPane.showMessageDialog(this,
                    "Tahun tidak valid!",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE);
                txtTahun.requestFocus();
                return;
            }

            if (stokInt < 0) {
                JOptionPane.showMessageDialog(this,
                    "Stok tidak boleh negatif!",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE);
                txtStok.requestFocus();
                return;
            }
            // ===== JIKA LOLOS VALIDASI =====
            System.out.println("Data valid, siap disimpan");

            // PANGGIL DAO SIMPAN DI SINI

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Tahun dan Stok harus berupa angka!",
                "Validasi",
                JOptionPane.ERROR_MESSAGE);
        }
        Buku buku = new Buku();
        buku.setJudul(judul);
        buku.setPenulis(penulis);
        buku.setPenerbit(penerbit);
        buku.setTahunTerbit(tahunInt);
        buku.setStok(stokInt);

        BukuDAO dao = new BukuDAO();
        dao.insert(buku);

        loadTable();
        btnResetActionPerformed(null);

        JOptionPane.showMessageDialog(this,
                "Data berhasil disimpan!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        System.out.println("Tombol Reset diklik");
        txtJudul.setText("");
        txtPenulis.setText("");
        txtPenerbit.setText("");
        txtTahun.setText("");
        txtStok.setText("");
        txtJudul.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahActionPerformed
        System.out.println("Tombol Ubah diklik");
        int tahunInt = 0;
        int stokInt = 0;
         // 1. cek apakah ID ada
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data yang akan diubah terlebih dahulu!",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. ambil input
        String judul = txtJudul.getText().trim();
        String penulis = txtPenulis.getText().trim();
        String penerbit = txtPenerbit.getText().trim();
        String tahun = txtTahun.getText().trim();
        String stok = txtStok.getText().trim();

        // 3. validasi kosong
        if (judul.isEmpty() || penulis.isEmpty() || penerbit.isEmpty()
                || tahun.isEmpty() || stok.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Semua field wajib diisi!",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
           
        // 4. validasi angka
        try {
            tahunInt = Integer.parseInt(tahun);
            stokInt = Integer.parseInt(stok);

            if (tahunInt < 1900 || tahunInt > 2026) {
                JOptionPane.showMessageDialog(this,
                        "Tahun tidak valid!",
                        "Validasi",
                        JOptionPane.WARNING_MESSAGE);
                txtTahun.requestFocus();
                return;
            }

            if (stokInt < 0) {
                JOptionPane.showMessageDialog(this,
                        "Stok tidak boleh negatif!",
                        "Validasi",
                        JOptionPane.WARNING_MESSAGE);
                txtStok.requestFocus();
                return;
            }

            // ===== JIKA LOLOS =====
            JOptionPane.showMessageDialog(this,
                    "Data valid, siap diubah",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            // PANGGIL DAO UPDATE DI SINI

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Tahun dan Stok harus berupa angka!",
                    "Validasi",
                    JOptionPane.ERROR_MESSAGE);
        }
        Buku buku = new Buku();
        buku.setIdBuku(Integer.parseInt(txtId.getText()));
        buku.setJudul(judul);
        buku.setPenulis(penulis);
        buku.setPenerbit(penerbit);
        buku.setTahunTerbit(tahunInt);
        buku.setStok(stokInt);

        BukuDAO dao = new BukuDAO();
        dao.update(buku);

        loadTable();
        btnResetActionPerformed(null);

        JOptionPane.showMessageDialog(this,
                "Data berhasil diubah!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        System.out.println("Tombol Hapus diklik");
        // 1. cek apakah ID ada
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data yang akan dihapus terlebih dahulu!",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. konfirmasi hapus
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);

        if (konfirmasi != JOptionPane.YES_OPTION) {
            return; // batal hapus
        }

        // 3. ambil ID
        int idBuku = Integer.parseInt(txtId.getText());

        // 4. hapus ke database
        BukuDAO dao = new BukuDAO();
        dao.delete(idBuku);

        // 5. refresh table & reset form
        loadTable();
        btnResetActionPerformed(null);

        JOptionPane.showMessageDialog(this,
                "Data berhasil dihapus!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked

    int row = tblBuku.getSelectedRow();
    if (row == -1) {
        return;
    }
    txtId.setText(tblBuku.getValueAt(row, 0).toString());
    txtJudul.setText(tblBuku.getValueAt(row, 1).toString());
    txtPenulis.setText(tblBuku.getValueAt(row, 2).toString());
    txtPenerbit.setText(tblBuku.getValueAt(row, 3).toString());
    txtTahun.setText(tblBuku.getValueAt(row, 4).toString());
    txtStok.setText(tblBuku.getValueAt(row, 5).toString());
// TODO add your handling code here:
    }//GEN-LAST:event_tblBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBuku().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollBuku;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btn_Ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblPenerbit;
    private javax.swing.JLabel lblPenulis;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblTahunPenerbit;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
